### ISSUE TITLE
Make the tooltip content interactable

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#1007]
Right now there are two issues that prevent users from interacting with the tooltip content (this makes it hard to have stuff like links inside a tooltip):
- A couple of elements in there have `pointer-events: none` set
- Tooltip goes away when you move the mouse off of the trigger element (unless you've actually focused the trigger element somehow)

For the first point, I can see that the tooltip contents are rendered inside a PopoverContent component, which is inside a Portal component, both of which have `pointer-events: none` set. I'm not sure yet if this is something we can simply remove, or instead have a separate interactable version of the Tooltip component which can be configured through props or something.

For the second point, I assume we're fine with making all tooltips stay open if the mouse moves on top of them, with some padded area between the tooltip trigger element and the tooltip contents.

**Comment by tec27** [comment]
> For the first point, I can see that the tooltip contents are rendered inside a PopoverContent component, which is inside a Portal component, both of which have pointer-events: none set. I'm not sure yet if this is something we can simply remove, or instead have a separate interactable version of the Tooltip component which can be configured through props or something.

You can simply apply `pointer-events: auto` to whatever child you want to accept pointer events, the ancestor's setting doesn't override that
