### ISSUE TITLE
Update the client's channel info state after user joins/leaves the channel

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#1026]
Since we keep the user count in the DB as part of the channel info, every time someone joins or leaves a channel (or gets kicked/banned), the client is left with a stale value for the user count.

User count is a part of `DetailedChannelInfo`, so we could just send this info as part of these chat actions. Or have the client update its own detailed channel info map for these actions?

**Comment by tec27** [comment]
This is only an issue for when you're in the channel, yes? Just update in the reducer when a join/leave happens?

**Comment by tec27** [comment]
Tbh I don't even know that it makes sense to use the data in this struct for displaying in the channel header, you may as well just use the info you know from the user list (although if/when we don't distribute the full user list for some channels that may get more challenging)

**Comment by 2Pacalypse-** [comment]
Yeah, this is only while you're in the channel. And yeah, I was specifically thinking of a time when we might not distribute the full user list.

My only dilemma was whether to actually send the `detailedChannelInfo` in join/leave/kick/ban events, or do the +/-1 math in the reducer for those actions. I think the latter is sufficient and easier to do.

**Comment by tec27** [comment]
Yes, I'd just increment/decrement in the reducer, that's how the reducers are meant to work

**Comment by 2Pacalypse-** [comment]
Done in https://github.com/ShieldBattery/ShieldBattery/commit/438f26a71419978072341fbce9e96059d57530a0
