### ISSUE TITLE
Wayland + virtual desktop: immediate crash

### ISSUE THREAD

**Issue by iopq** [ShieldBattery/ShieldBattery#1030]
Steps to reproduce:

1. On a new prefix, set the virtual desktop setting to on
2. Install shield battery
3. Crash when on Wayland, fine on Xorg

you can also disable the virtual desktop and it will be fine on Wayland too

here's a backtrace
[backtrace.txt](https://github.com/ShieldBattery/ShieldBattery/files/12485345/backtrace.txt)

**Comment by tec27** [comment]
Don't think there's anything to be done on our end with this. ShieldBattery is just an Electron app (e.g. Chromium), we don't do anything have any code involving rendering, virtual desktops, etc. within the app code, it's all stock Electron stuff.
