### ISSUE TITLE
Fix multi-line text-field and textarea spacing/padding

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#1068]
This is how it currently looks (I think it's even worse when there are trailing icons):

![image](https://github.com/ShieldBattery/ShieldBattery/assets/4757944/4dbc5c3d-0465-435b-8db0-580158276ac3)

**Comment by tec27** [comment]
The component also doesn't resize correctly if it has a multi-line value on first render (e.g. `rows=1`, `maxRows=4` with a multi-line value will leave it at 1 row)
