### ISSUE TITLE
Text field has unnecessary top padding when no label is present

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#1075]
Repro:
1) Open Maps sidebar
2) View details on a map you can edit
3) Click the edit button on the description

Expected: The content would have symmetrical padding at the top (and the scrollbar would reach the top of the element?)
Actual: The scrollbar and all content is padded down to make space for a label that doesn't exist

**Comment by 2Pacalypse-** [comment]
This actually doesn't seem that easy to fix from what I can tell. It seems like `textarea` and `input` do vertical alignment of text inherently different. For example this is how text gets aligned on a single-row `textarea` field (notice the text cursor):

![image](https://github.com/ShieldBattery/ShieldBattery/assets/4757944/08de65ca-2d7a-4f7b-8948-ae05cd7f6ad3)

And this is how it looks like on an `input` field:

![image](https://github.com/ShieldBattery/ShieldBattery/assets/4757944/e8501f02-d510-41e5-a0b9-a929ae747aad)

Both of them have the same top padding. So to align the text over the placeholder in textarea, I have to set its top padding to `19px` (and `11px` for dense textarea). Which doesn't make it symmetrical with the `12px` left padding, and setting all of padding to `19px` seems a bit much.

**Comment by tec27** [comment]
I'm not really sure what you're saying tbh

This is what I want fixed:
![image](https://github.com/ShieldBattery/ShieldBattery/assets/360513/401a1251-03e4-4d55-949c-5f23bca28d18)

The scrollable area needs to be the whole box, not the whole box minus whatever the top padding is set to. I'm not really sure why the layout of single-line and multi-line inputs really matters, given that we already have to make the decision to render one or the other, can we not also make the decision to style them differently?

**Comment by 2Pacalypse-** [comment]
Ah ok. Yeah, that is easily fixed.
