### ISSUE TITLE
Add more info to the whisper page

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#1099]
Currently the whisper page looks pretty barren, especially if you don't have any messages in there. At the bare minimum we can add the profile info of the user we're whispering with, similar to how we display users in the regular chat channels. However, we could also think about making the design of the whisper page more special, to differentiate it from regular chat channels a bit more.

**Comment by tec27** [comment]
The intention was to put user profile info on the right side

**Comment by 2Pacalypse-** [comment]
Yeah, I was just wondering what's the best design for that. Do we just use the same design we use in regular chat channels for users list, or do we have a bit more special design to display the user profile info since there will only be one user there (unless we add support for private group chats at some point :p).

**Comment by tec27** [comment]
I would just replace the user list area from chat channels with information about the user. Discord does this reasonably I think
