### ISSUE TITLE
Can I ask a question about replay?

### ISSUE THREAD

**Issue by lpflhh** [ShieldBattery/ShieldBattery#1113]
Can I ask a question? How to play a replay file independently? Thank you

**Comment by tec27** [comment]
If you're asking how we launch replays, it's the same method we use to launch normal games (we have an injected DLL that triggers the various parts of SC:R's initialization and then loads the specified map/replay programmatically). This isn't something that would be usable outside of ShieldBattery, if that's what you're trying to do
