### ISSUE TITLE
Graphics glitch, rendering starts halfway down the screen

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#217]
##### This is a migrated issue from the old repo: https://github.com/tec27/shieldbattery-old-do-not-use/issues/107

http://i.imgur.com/Tw9OYeJ.png

ICanFlyLow ran into this, said he was running ICCup (full screen) and playing ShieldBattery. He closed the ICCup copy mid-way through the game (likely triggering a display resolution change back and forth) and when he went back to the SB version, saw what the screenshot shows.

**Comment by tec27** [comment]
Closing as obsolete, we can re-open if we see this again.
