### ISSUE TITLE
Investigate moving DX/GL rendering off the main thread

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#219]
##### This is a migrated issue from the old repo: https://github.com/tec27/shieldbattery-old-do-not-use/issues/71

Since BW is CPU bound (even if artificially) and our newer rendering technologies have different performance characteristics than it was originally designed for, I think they can cause a few problems with its rendering.

Namely, we try to skip render passes that would be completely unnecessary (because they'd be rendering multiple times in the same frame). This is actually kind of bad, because the render pass we keep might be the one that happened at the beginning of a particular vsync cycle, thus giving the user the least up-to-date frame that we received.

The main reason we need to do this is because certain operations will begin to block if we deliver them too many frames ahead of time (that is, delivering 2 or more frames within a cycle) (OpenGL SwapBuffers calls do this, for example). Since we're on the same thread SC uses for game logic, blocking is not an okay thing to do. If we pushed all of our rendering to a separate thread that merely read from surface data as it wanted to render, we could render at a framerate completely distinct from SC's rendering, and hit the frame timing ~every time always with the most up-to-date surface data we have. We could also actually make use of vsync, since blocking the thread that only does rendering would be fine.

**Comment by AleXoundOS** [comment]
Is it still an issue with SC:R?

**Comment by tec27** [comment]
Not really, no
