### ISSUE TITLE
Add an option to start our application automatically when OS starts.

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#276]
Maybe we could use this library to do it more easily - https://www.npmjs.com/package/auto-launch

**Comment by 2Pacalypse-** [comment]
Looks like this is supported by Electron out of the box now and seems to be fairly straightforward to implement:
https://www.electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows

We would also need an option in system tray menu to toggle this option though (perhaps even one in the settings dialog?).

**Comment by tec27** [comment]
Settings dialog seems like a better spot for it, yeah :)
