### ISSUE TITLE
Implement method for re-processing maps in case of map parsing/etc. bugs

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#286]
If bw-chk or whatever other part of our map upload process parses map data incorrectly, we'll need a way of triggering specific maps to be re-processed. Since the vast majority of maps seem to work, this could probably be done on a per-map basis (maybe as part of whatever admin tools we implement to manage uploaded maps?)

**Comment by 2Pacalypse-** [comment]
Done in 5c363041dee31731472a92ea00fdaa547979ba78
