### ISSUE TITLE
Replace dbClient.queryPromise usages with dbClient.query

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#306]
node-postgres clients implement Promise now (if no callback is passed), so we can remove the `queryPromise` implementation we set up and just use `client.query` everywhere

**Comment by 2Pacalypse-** [comment]
Done in https://github.com/ShieldBattery/ShieldBattery/commit/4ee81e0655e8586bf16e8b42ba49ef0d7e9a8e96
