### ISSUE TITLE
Spin-up a couple of more servers for rally-point

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#317]
The important one is to get a Korean one imo. South American one could be useful as well.

**Comment by tec27** [comment]
GCP and AWS both have a region in Seoul now, as well as one in Brazil. Both also have one in Australia that may be good if we have a significant number of users there. (It'd be nice to be able to spin these up/down more dynamically at some point. If we were only running these servers when we actually needed them, we could cover a lot more regions cheaply)
