### ISSUE TITLE
Upgrade to react-router 4.x

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#330]
API has changed (somewhat significantly), so we'll need to fix everywhere we make use of this. In general I don't see anything incompatible with the changes they've made, but it'll result in us reorganizing our route setup.

(The older version causes a warning about React.createClass in React 15.5+)

**Comment by 2Pacalypse-** [comment]
Done in https://github.com/ShieldBattery/ShieldBattery/commit/86858a5679a66b656928553b1dbbd69637290c2d

And let me just say, putting "good first contribution" label on this was a mistake :P
