### ISSUE TITLE
Devise and implement an error code system

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#331]
We need an error code system in numerous places in the app (generally all the places we do some type of RPC):

- HTTP APIs
- Nydus APIs
- Communication between StarCraft processes and client apps
- etc.

HTTP error codes are nice, but don't get specific enough to do things like give useful error messages to users, and parsing/matching English error messages is just a bad idea. We need a system that passes back error codes (ints, matchable strings, whatever, just some form of constant) that we can use to decide behavior.

This sort of thing becomes especially important as we implement matchmaking, where we need to be able to decide between "permanent" failures (this user will never be able to successfully join a game until they fix some issue in their setup) from "transient" ones (something weird happened this time, but it will probably work next time), and also where we need to be able to assign "blame" (a user with a permanent failure needs to be removed from the queue, a user with a transient one, or who was affected by a different user with a permanent failure can stay).

A basic system that would work is to use a `code` value on Error objects (like nodejs built-in APIs generally do), but we need a general pattern for how to use these, what the code values are, etc.

**Comment by 2Pacalypse-** [comment]
I think we have a pretty decent way to handle errors now so I'm gonna close this.
