### ISSUE TITLE
Implement matchmaking map pool support

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#334]
To support matchmaking alongside our map system, we'll need something that doesn't require hardcoding maps for it (as we don't really have a guarantee that certain maps will be available on every server, and we also don't want to be forced into doing server releases alongside map changes/ladder season changes).

We need something that:

- Can be changed by relevant admins
- Can be looked at historically (e.g. what was the map pool for season 1?)
- Can be changed in the middle of ladder seasons (e.g. map X has a bug or is severely imbalanced and has an updated version, or perhaps we just made a terrible map choice)
- Can be set to change at a particular time in advance (so we don't depend on admins being around and doing something at an exact time)

## Proposed system:

- Add a new permission, `manage_map_pools`

- Create a new table in the DB, `matchmaking_map_pools`. Structure:

```
id int (autoincrement, primary key)
matchmaking_type enum (should use whatever enum we use elsewhere for these, for now this enum can just contain a single value [1v1])
start_date datetime
maps bytea[] (same as PK of the maps table)
```

The entry with the latest start date that is before the current date would be the "current" map pool.

API should prevent insertion of anything earlier than the current date.

- Clients are able to request the current map pool from the server, at which point we resolve the map keys to real map data, and make sure to include the ID of this pool. If the pool is the same as the one the client has saved preferred maps for (or they don't have preferred maps saved), cool deal, display it and continue on. If the ID is different, display a warning of some sort around the map selection UI to let them know that they may want to change their selections (but still apply preferred status to any maps that are still in the new pool). We won't subscribe clients to any changes to this data, but would re-request it when they open the 'find match' interface (with some fairly low cache time). If they request to find a match and the map pool has changed since they last requested the data, we can either kick them back to that screen with an error, or continue anyway (I think I prefer the former but it might need some testing with real users).

(Above talks about saving preferred maps, the data/API structure for that will be in a separate issue from this one)

- Admin interface could display current and upcoming map pool changes (or maybe just all? This shouldn't change that often/be that large)

**Comment by 2Pacalypse-** [comment]
This is now done in https://github.com/ShieldBattery/ShieldBattery/commit/74da6bed5e951a776920748047905d2ed94dde97 and https://github.com/ShieldBattery/ShieldBattery/commit/f2560743a462d361fee8b66873dfe80fe999d10e (among few other commits)
