### ISSUE TITLE
Implement matchmaking map preference saving

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#335]
Having map preferences will be very annoying if we don't save it between sessions, so we need to do that :)

## Proposed system:

-  Create a new table `matchmaking_map_preferences`:

```
user_id (int)
matchmaking_type enum (matches the one in the matchmaking_map_pools table)
map_pool_id (int)
preferred_maps bytea[]

PK is (user_id, matchmaking_type)
```

- API allows users to modify and retrieve their own map pool only, and only prefer a limited number of maps (2)
- Find match UI would retrieve this data when shown, but also pass the preferred maps directly to the matchmaker (seems preferable to utilize the preferences displayed to users, even if they're outdated by the time they hit find match due to other clients updating the info). When preferred maps are edited (e.g. they click into the secondary UI), they'd be sent back to the server to update the stored data
- Map pool ID is used to know when the selections are potentially outdated and a notification/warning should be shown to users.

**Comment by 2Pacalypse-** [comment]
Do you think it would be ok to forgo saving the `map_pool_id` here, and instead just compare each of the maps in `preferred_maps` array with the maps in the current map pool? It would be a small performance penalty and in turn we can get a nicer UX, where even if the map pool changed, but all of the user's preferred maps are also in the new map pool, user can just carry on without receiving a warning that a map pool changed. And even in cases where only some of the preferred map(s) have changed, we can only highlight those that have changed in UI, so the user knows which map(s) need to be replaced.

**Comment by tec27** [comment]
The `map_pool_id` is meant to prevent them from updating preferences for a map pool that is no longer valid, not to preclude you from doing other things on top of that system. If you want to provide a new set of preferences automatically, I'd probably just do that on the client.

e.g.
```
if (mapPoolId !== currentMapPoolId) {
  oldMapPool = retrieve(mapPoolId)
  newMapPool = retrieve(currentMapPoolId)
  mapPrefs = createNewMapPrefs(oldMapPool, newMapPool)
  saveMapPrefs(mapPrefs)
}
```

I certainly don't think constructing map preferences on the fly every time is going to be a good idea, those queries are going to be very complicated and error-prone and the likely case is that if map changes are very slight, people will just tend to ignore the map pool changes and you'll *always* be doing those complicated and error-prone things on every query.

If you want to display what maps are "new" you could add a field to this table that says whether the entry was an "auto-migrated" one, and then select for the last entry that wasn't auto-migrated in order to compare.

**Comment by 2Pacalypse-** [comment]
Hmm, the way I imagined implementing this, and please let me know if you think this approach is bad, is to have these matchmaking preferences be more like find-match overlay preferences. Sort of like the ones I already implemented for the create-lobby and map-browser. What this means is that we just save the current "state" of the overlay every time it's closed, and restore it to that saved state when it opens.

With that approach, the things we would save in the DB are the following:
```
user_id (int)
matchmaking_type (matchamking_type_enum)
active_type (matchmaking_type_enum)
race (race_enum)
use_alternate_race (boolean)
alternate_race (race_enum)
preferred_maps (uuid[])

PK is (user_id, matchmaking_type)
```
So, we wouldn't really have any complicated logic saving that data in the DB; just dump whatever user sends. And when we fetch those preferences (when a find-match overlay is opened), we initialize it with all of the saved state, and also get the current map pool. Then we can, on the client, just check if the preferred maps are still in the current map pool and display the results in any way we want. Also, matchmaker service can get the same data on the server, and decide what to do if a user tries to play with an outdated preferred map.

Please let me know if I'm missing something, which is very likely ^^.

**Comment by tec27** [comment]
I don't think that's particularly problematic, but it doesn't really provide an opportunity to notify people that the map pool has changed (we can only determine that if they had banned one of the maps that got removed from the pool). You could solve that by storing the map pool ID in that info as well (and use that to show a notification/icon/etc. in the UI, select the old + current map pool for identifying changed maps, etc.). Otherwise that seems fine, don't see much of a reason to have a table *just* for the map selections

(And to be clear, in that world, opening the map selection UI with an outdated map pool ID would save the row with the updated one + just the currently applicable maps in `preferred_maps`)

**Comment by 2Pacalypse-** [comment]
Oh, I think I didn't express myself correctly. What I'm suggesting is that this would be the _only_ table regarding the matchmaking preferences; there wouldn't be a separate one for map selections. Opening a map selection UI would just get the _current_ map pool and the preferred maps would be sent as props from the find-match overlay (I actually already implemented this in the find-match branch). This way, the user doesn't really care about the map pool _ID_, just if any of their preferred maps are still viable in the _current_ map pool.

But actually now that I think about it, I think I get what your concern is. Which is that we can't tell the user that a map pool changed if both of their preferred maps are still available in the new map pool. Hmm, I was thinking we wouldn't even notify the user in that case, but I guess I can see the benefit of letting them know that the map pool changed, so they can revise their selections, if they want.

So yeah, I think we can just save the map pool ID in the table above as well; it doesn't really add any further complexity, and gives us more info to determine things ^^.

**Comment by tec27** [comment]
> What I'm suggesting is that this would be the only table regarding the matchmaking preferences; there wouldn't be a separate one for map selections.

Yeah I understood that, I was saying that was fine. 

And yeah, my main concern was about notifying users that the pool had changed. As it is now (on Blizzard ladder or whatever) it relies on them reading news or whatever to find that out, and I think it'd be nice to show them that information within the UI for finding a match (even if it's just a little indicator icon next to the map pool or something). Not *forcing* users to re-select the same maps just because the pool has changed is a fine/welcome change. Saving the pool ID in the table just gives us the ability to easily decide when to show/hide that notification (and something to key off of when adding "new map" or whatever indicators to the selection UI).

**Comment by 2Pacalypse-** [comment]
Yeah, I agree with that. It shall be done.

**Comment by 2Pacalypse-** [comment]
This is now done in https://github.com/ShieldBattery/ShieldBattery/commit/cdaeadf2d69acbca1e6654d44ecff7e9cc2db7c5 and https://github.com/ShieldBattery/ShieldBattery/commit/22b40cf71ea3b0cdc60ff390b81ba7e693cc5fd8 (among few other PRs)
