### ISSUE TITLE
Account creation should trigger a verification email

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#340]
We want to ensure our user accounts are created with valid email addresses, so that they have some recourse should they e.g. forget their password. This is something that was often problematic with beta signup: since we never sent them an email on signup, users either A) didn't know what to expect when they got our invite email or B) signed up with an incorrect email address and never realized. This also assists users down the road when they want to figure out what email address they signed up with: we can guarantee they've received an email from us in the past.

We should follow typical practices for web apps, which are:

1) When the user creates their account, we send them an email with a verification link
2) They get logged into the site, and we display a warning of some kind that they haven't yet verified their email address, offering to send them another verification link if they desire (this would be heavily rate-limited to prevent spam, like all of our email functionality). The verification code could either be stored in the DB (like password reset codes), or be a signed request combining username + email address + some unique/random value
3) Once a verification link is clicked for their current email, we mark that address as verified in the DB and cease displaying warnings to them.
4) Allow users to change their current email address in their profile. Changing email address triggers an email to the previous address notifying them that the change occurred, as well as marking the user as unverified and redoing the above cycle.

**Comment by 2Pacalypse-** [comment]
Done in 42a630805783275897944d6c69896aa1122f836f and a63c19b0230e6fd58020afd036acb53446fafb54
