### ISSUE TITLE
Consistent autoreplay directory with 1.18

### ISSUE THREAD

**Issue by neivv** [ShieldBattery/ShieldBattery#343]
We currently save replays to `documents/starcraft/maps/replays/auto/`, while bw 1.18 saves them to `documents/starcraft/maps/replays/autosave/YYYYMMDD/HHMMSS-{map filename truncated}.rep`.

I don't know if it's a good idea to just mix our replays with 118 ones, but having two directories named auto and autosave is really confusing.

**Comment by tec27** [comment]
SC:R handles it's own autoreplay now so gonna close this.
