### ISSUE TITLE
Changing one element in a form can cause another element to be unnecessarily validated

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#378]
I've noticed this in the SignUp form when a username is entered, that element is marked as "dirty". However, it's not removed from the list of "dirty" elements once the validation ends, which means that when you focus on any other field and start changing it, the validation of the username will keep firing, which is not an inexpensive operation since it fetches username availability from the server.

**Comment by tec27** [comment]
`dirty` means "this element has changed from its default value", *not* "this element has not been validated". Validations can have dependencies on other elements, and we have no way of knowing what their dependencies are. Thus, changing one element can affect the valid status for a different element, and  validity has to be re-checked each time.

If this were actually an expensive operation, I'd be worried and maybe try to mitigate it, but checking username availability is not.
