### ISSUE TITLE
Map distribution system

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#404]
ShieldBattery's map system is designed to have three major goals:
1. Easily find known and popular maps
2. Organize your own maps and have them available in the cloud
3. Explore new and interesting maps from community members

The map manager that will be used by users is split into three tabs where each tab will serve the purpose of one goal. The first goal will be served by an OFFICIAL MAPS tab, where admins will make a curated list of popular and known maps and keep it updated, so the users should never need to worry about their versions. The second goal will be served by a MY MAPS tab, where users will have a lot more freedom in what they can do. Anytime they select a local map directly from their computer, that map will automatically be updated to their private maps list. This list will also show all of the maps they've favorited, no matter who uploaded it. They will have the ability to update and remove their private maps, as well as submit them to be made public, which leads to the third goal. COMMUNITY MAPS tab is a place for map makers and community members to meet and benefit from each other. Map makers will have the ability submit their private map to a review process and if approved by an admin, will be added to the list of public maps that other users will be free to explore and test new maps. Once made public, user's map will only be updateable by an admin or if the owner of the map gains enough trust to be given special privileges.

### Create
- User can upload a map implicitly when creating a lobby (uploads as a PRIVATE map)
- User can upload a map explicitly through a map manager (uploads as a PRIVATE map)
- Admin can upload an OFFICIAL map

### Read
- User can view their PRIVATE maps in the "My Maps" tab (along with all the maps they favorited, regardless of their visibility)
- User can find their PUBLIC map in the "Community Maps" tab
- User can view PUBLIC maps from other users in the "Community Maps" tab
- User can view OFFICIAL maps in the "Official Maps" tab

### Update
- User can update their PRIVATE maps
- Admin can update OFFICIAL maps
- Admin can update PUBLIC maps
- User can favorite any map
- User can submit their PRIVATE map to be made PUBLIC (needs admin approval)
- Admin can approve user's request to make their PRIVATE map PUBLIC
- User with special permission can update their PUBLIC maps

NOTE: Only name and description are updateable properties of a map for now

### Delete
- User can delete their PRIVATE map (a soft delete)
- Admin can delete an OFFICIAL map (a soft delete)
- Admin can delete a user's PUBLIC map (a soft delete)

## DB Schema
Tables used to implement the map system in the DB are:

`maps`:
```
hash PK (bytea)
extension (char3)
title (text)
description (text)
width (integer)
height (integer)
tileset (integer)
players_melee (integer)
players_ums (integer)
lobby_init_data (jsonb)
```

`uploaded_maps`:
```
id PK (uuid)
map_hash (bytea)
uploaded_by (integer)
upload_date (timestamp)
visibility (map_visibility_enum)
name (text)
description (text)
removed_at (timestamp)

UNIQUE (map_hash, uploaded_by, visibility)
```

`favorited_maps`:
```
map_id PK (uuid)
favorited_by PK (integer)
```

(TODO)`map_versions`:
```
map_id PK (uuid)
version PK (integer)
map_hash (bytea)
changelog (text)
uploaded_by (integer)
upload_date (timestamp)
```

A few things to consider:
- If a user's PRIVATE map is approved to become PUBLIC, it will basically make the user relinquish all rights to it (TODO: make sure this is properly communicated to the user before they commit to it). They will still be listed as the person who uploaded it, but they won't be able to either update or remove it; unless they're granted special privileges by an admin.
- It might be worth adding a separate `author` column to the `uploaded_maps` table, that will be shown for the PUBLIC maps, instead of `uploaded_by` column (as they might not be the same person).
- Deleting maps entirely from the system is not supported as such. However, maps can be removed from the listings API, while still being used in other APIs (eg. matchmaking map pools, recent maps list, replays, etc.).
- Updating a non-PRIVATE map is only possible by an admin and by users with special permissions (who will be able to only update their own PUBLIC maps)

### Map statistics
One thing that is still unclear on how it should be done is tracking map statistics. Probably the most useful example of this is calculating the map's "popularity" (eg. hosted_count + joined_count). The most correct thing would probably be to track map statistics for each row in the `maps` table, instead of tracking statistics for each row in the `uploaded_maps` table, but this is still something that remains to be seen on how it should actually be implemented.

### Duplication
Another thing that needs some special thinking is better handling of duplicate/similar maps. One way this could be handled is by doing the following: When user tries to upload a map (either through Create Lobby workflow or directly trough map manager), the SB will automatically detect same/similar maps (by doing hash matching, hash terrain matching, or even thumbnail image similarity algorithms) and offer a user the choice - do you want to use the existing, similar map, or do you want to upload the map anyway. For this to work, there needs to exist the "base" map which will be used to compare all other maps to. Without introducing a separate concept of "base" maps and tracking them independently, we can just use OFFICIAL maps as the "base" maps. So the newly uploaded maps will only be compared to the OFFICIAL maps, and if there's no same/similar map in the OFFICIAL maps, but there is in PRIVATE/PUBLIC maps, we don't offer a user the choice to use a different map and just upload whatever they selected.

### Cloud-based storage
Another thing is that we'll probably have to switch to cloud-based hosting of maps at some point. This shouldn't be too hard, but there's some things to take into consideration, like generation/optimization of map's thumbnail image, etc.

### Reprocessing
At some point, we'll need to add a way to reprocess an already uploaded map. For example, map image generation can fail; and at this point, we upload the map without an image just fine. But it might be useful to add a way to try to generate a map image again in case it failed, or in case we've changed the way in which we're generating map images.

**Comment by tec27** [comment]
@2Pacalypse- can we figure out what's still left to be done here and split that off into separate issues?

**Comment by 2Pacalypse-** [comment]
Honestly, I would just leave it for now. Most of the stuff left is pretty vague at the moment and requires some more thought in how to design them, so I'd rather open an issue for them once we get to that point.

I'd just close this issue for now as its main design goals have been implemented.

**Comment by 2Pacalypse-** [comment]
I can see now how my "leave it for now" comment might have been misinterpreted :d. What I meant was to leave the creation of separate issues for now and instead create them when we actually put some more thought into what's missing and how to design them.

So just gonna close this issue and consider this feature a huge success!
