### ISSUE TITLE
SC:R Support

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#453]
This document outlines most of the things that we should do before we can say that we "support" SC:R. I already had this lying somewhere in my gists, so just making an official issue out of it now so the progress can be easily tracked.

### Error-handling / Debugging
- ~~Make sure all game-related errors are properly handled in the app (usually just means canceling the game starting and displaying a message in the lobby chat; for replays display an error in a dialog?).~~
- ~~Try to avoid "hard crashes" (which display cryptic message boxes) and instead try to show any pertinent information to the user in the app.~~
- ~~For all other errors, make sure they're logged somewhere that is easy for the user to find and send to the admin if requested (try to keep the number of log files to a minimum).~~
- ~~Make a manual end-to-end test to make sure all code paths from starting a lobby -> game start -> game end are either properly handled in case of an error, or logged properly~~
- ~~Make sure the app is never left in a broken state due to a game error (for example, if the StarCraft process is not properly cleaned up etc.)~~

### Downgrade system / Version tracking
- ~~Clean up the downgrade code; currently, the downgrade system doesn't seem to be necessary at all. ShieldBattery should work automatically for new SC:R versions, barring no huge patches.~~
- ~~Figure out a best way to turn the downgrade code "off" for now to not cause confusion, while still leaving the option of implementing a SC:R supported downgrade system sometime in the future.~~
- ~~Implement a code that tracks the user's StarCraft version (save it to the database?), which will give us an easy way to offer client-side protections for unsupported versions.~~

### Performance improvements
- ~~Look into starting the StarCraft process earlier (as soon as the countdown starts?)~~
- ~~Investigate why there's a long "black screen" after the game starts (sprite loading?) and see if it could be mitigated (might be fixed automatically by doing the first thing and hiding the StarCraft window until everything finishes loading?)~~

### Forge refactor
- ~~Remove the hacky code from forge~~
- Update the forge to be a unified interface that sits on top of both the 1.16.1 and SC:R rendering
- Make it possible for forge to run different features based on the StarCraft version
- Figure out which features make sense for which StarCraft version

### Settings update
- ~~Refactor the StarCraft path checking~~
- ~~Expose an easy way throughout the app to check if the current StarCraft path is SC:R or not~~
- ~~Make the settings dialog clearly show if the path is SC:R or not~~
- ~~Disable/enable setting options depending on which version of StarCraft it is and whether they make sense for that version~~
- ~~Saving the settings from inside the SC:R game doesn't work~~
- ~~Changing the video mode inside the SC:R game crashes the game (and hangs the process)~~
- Hook into StarCraft's settings and combine it with our own

### Multiplayer support
- ~~Make the basic game between multiple people work~~
- ~~Support Team Melee game types (and any other that might not work in the basic version)~~
- Explore how the dynamic turn rate setting works and determine if it's worth implementing our own version

### Observing support
-

### Interoperability between StarCraft versions (mainly 1.16.1 <-> SC:R)
-

### SC:R's custom hotkeys
- ~~See if there's a way to load the custom hotkeys that a user might have for their battle.net profile~~

### HD Gfx
- SC:R helpfully disables HD graphics if the user doesn't log into battle.net in a month. Try to do this automatically for users through the available battle.net APIs

### Replays
- ~~Fix rewinding back in SC:R replays; when rewinding back in replays, SC:R stops the game loop and starts from beginning which makes us exit the game~~
- Communicate an error to the user if they try to watch a SC:R replay with 1.16.1 version
- App should cleanup BW if the replay launching fails (can be tested by trying to play SC:R replay with 1.16.1 version until the above fix is done)

### Move the WinProcess native module to Rust
- When `neon` adds `N-API` support - https://github.com/neon-bindings/neon/issues/444
- Refactor the code to better support multiple ways of launching the process

**Comment by Brooooooklyn** [comment]
https://github.com/napi-rs/napi-rs has already supported N-API

**Comment by tec27** [comment]
I think this is all basically done (not necessarily in the way described here, but handled well enough), so I'm gonna close this
