### ISSUE TITLE
Follow Electron security best practices

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#457]
I don't think this list (or even a number of these features) existed when we first made this, but it'd be good to follow now:

https://www.electronjs.org/docs/tutorial/security

Some of it will require some restructuring of how things work, but I think most of it should be straightforward (or already set up).

**Comment by 2Pacalypse-** [comment]
This seems related :d - https://news.ycombinator.com/item?id=24822755
