### ISSUE TITLE
Doing two file browser dir changes in quick succession can cause contents get desynced from displayed directory

### ISSUE THREAD

**Issue by neivv** [ShieldBattery/ShieldBattery#486]
In replay/map browser, select a directory, and then use the top bar to select the parent directory you were in a few seconds ago.

If the child directory's I/O takes longer than the parent's (especially when the parent directory is in OS-level cache and child is not), the file browser ends up showing contents of child directory but with path of a parent directory.
<details>
  <summary>Redux messages if that clarifies what is happening:</summary>

```javascript
{
  type: 'FILE_BROWSER_CHANGE_PATH',
  payload: {
    browseId: 'replays',
    path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays\\Auto'
  }
}
{
  type: 'FILE_BROWSER_GET_LIST_BEGIN',
  payload: {
    browseId: 'replays',
    path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays\\Auto'
  }
}
{
  type: 'FILE_BROWSER_CHANGE_PATH',
  payload: {
    browseId: 'replays',
    path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays'
  }
}
{
  type: 'FILE_BROWSER_GET_LIST_BEGIN',
  payload: {
    browseId: 'replays',
    path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays'
  }
}
{
  type: 'FILE_BROWSER_GET_LIST',
  payload: [
    {
      isFolder: false,
      name: '144057-ICCup Fighting Spiri',
      path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays\\144057-ICCup Fighting Spiri.rep',
      extension: 'rep',
      date: '2017-11-30T18:30:43.645Z'
    },
    // *snip*
  ],
  meta: {
    browseId: 'replays',
    path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays'
  }
}
{
  type: 'FILE_BROWSER_GET_LIST',
  payload: [
    {
      isFolder: false,
      name: '00001_2019-04-25',
      path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays\\Auto\\00001_2019-04-25.rep',
      extension: 'rep',
      date: '2019-04-25T16:31:46.687Z'
    },
    // *snip*
  ],
  meta: {
    browseId: 'replays',
    path: 'C:\\Users\\Markus\\Documents\\Starcraft\\maps\\replays\\Auto'
  }
}
```
</details>

**Comment by 2Pacalypse-** [comment]
I tried reproducing this, but it seems almost impossible with an SSD :p

But yeah, I see what's happening. Guess we need to check if the get-files action `isRequesting` and cancel the previous promise (which we now need to save in store) if it does. Shouldn't be a problem, although I'm not sure what's the best way to "cancel" a promise without rejecting it with an error; maybe resolving it with some bogus value?

**Comment by neivv** [comment]
I think we could let the request finish and ignore FILE_BROWSER_GET_LIST in the reducer when the path in that action doesn't match the path in state? That is, assuming that the path that is in the state can be considered to always be 'correct' and representing the directory we want to display.

**Comment by 2Pacalypse-** [comment]
That could work too, I think. And it's probably easier to implement as well.

And yeah, I think ensuring that the displayed path and the fetched files are consistent with each other is a good idea, regardless of this specific bug (with displayed path being the source of truth).

**Comment by 2Pacalypse-** [comment]
Fixed in https://github.com/ShieldBattery/ShieldBattery/commit/e64d8a5bedc072d5915f7bd7ab564e0cbca40de2
