### ISSUE TITLE
Stop using `KeyboardEvent.which` property and remove the "keycode" library

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#492]
Seems like the they `KeyboardEvent.which` property is now deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which

And the recommended way is to just use the `KeyboardEvent.code` property: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

We're already mostly using `KeyboardEvent.code` property, but there are still some places where the `KeyboardEvent.which` property is used and those should be updated.

**Comment by tec27** [comment]
99% sure this property was also deprecated when all of this stuff was implemented, but the suggested replacement either wasn't very widely available, or didn't actually present useful functionality for what we were trying to do. May want to make sure it actually meets all of our use cases before going down that path (especially since React is also the one wrapping these events and providing these properties)

**Comment by 2Pacalypse-** [comment]
Took me a while, but I just now fully realized what you mean by React wrapping these events (I was only vaguely familiar with that). But yeah, they haven't yet implemented support for the `.code` property: https://github.com/facebook/react/issues/12902

However, two things:
- you can still access the native event from the react event by using the `.nativeEvent` property (which is kind of a pain)
- but also, I just checked and we only use React's `onKeyDown` event at a single place; the Slider component, which I now also moved to using our generic `KeyListener` component (which is using native events directly, instead of going through React)

So this issue could still be done, if we're ok with recommending usage of our `KeyListener` component instead of using React's synthetic events system. I think that might be fine since we're now using it pretty much everywhere anyway. And from what I can see, this `KeyListener` component serves pretty much the same purpose as hooks do (and does so without any new APIs!) 😛.

**Comment by 2Pacalypse-** [comment]
After some more discussion, I now know that `KeyListener` should not really be used for non-global hotkeys, as every KeyListener attaches new handlers to the document and has to call through to them on every keypress.

So gonna close this issue for now since going with the first option (of using React's `.nativeEvent` property) is too much of a pain for not a lot of gain.
