### ISSUE TITLE
Matchmaking preferences default to Zerg

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#510]
Don't want to make it seem like we're biased in any way, this should probably be random 😃

**Comment by 2Pacalypse-** [comment]
I think I picked Zerg as its the first race in our race picker 😄
If we use random as the default value there, what should be the default value for alternate race though?

**Comment by tec27** [comment]
I think probably the first available race that isn't the same as the one they picked, maybe (e.g. P if they picked Z, Z otherwise)? Or Z is fine there, I think that's less of a big deal
