### ISSUE TITLE
Implement the UI for SC:R settings in the app

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#514]
This issue concerns only the UI side of the SC:R settings; connecting them with the game can be done separately as it requires a different kind of skillsets :d

Also, implementing the UI for custom hotkeys is a separate issue as well, as it requires some further thinking in what that implementation should look like.

**Comment by tec27** [comment]
While you're doing this it would be helpful to look at the existing SC:R settings file and document its format. For one, because it will help you understand what settings are actually available to change/how they are controlled, but also because it will make the future work of integrating this with the game easier.

**Comment by 2Pacalypse-** [comment]
Gonna post here screenshots of all the settings so it's easier to have a reference (this is not a proper documentation tho):

![image](https://user-images.githubusercontent.com/4757944/94940540-eade9b80-04d3-11eb-9db1-712d61159530.png)

![image](https://user-images.githubusercontent.com/4757944/94940577-f762f400-04d3-11eb-9c01-93f034765329.png)

![image](https://user-images.githubusercontent.com/4757944/94940632-09449700-04d4-11eb-9095-f1b662b6ff93.png)

![image](https://user-images.githubusercontent.com/4757944/94940661-1497c280-04d4-11eb-8be0-c7af709e76ce.png)

![image](https://user-images.githubusercontent.com/4757944/94940708-24afa200-04d4-11eb-95bb-f2283d57f8b1.png)

**Comment by 2Pacalypse-** [comment]
Assuming we implement all of these (well, except Network ^^), should we split them in the tabs with the same name in our settings too?

**Comment by tec27** [comment]
I would rethink whether the sorting makes sense. For a lot of things it seems fine, but 'Speed' is a terrible categorization and it makes zero sense to have 'Game Speed' alongside 'Mouse Sensitivity', so there's probably other things in there that could be categorized better.

Input/Sound/Video/Gameplay is maybe sensible.

**Comment by 2Pacalypse-** [comment]
So you wouldn't put 'Game Speed' under the Input tab at all? I guess it would make more sense under the Gameplay tab.

Another thing that I wanted to ask is about this TODO I left here:
https://github.com/ShieldBattery/ShieldBattery/blob/master/client/settings/settings.jsx#L161

Do you think we should save the changed settings only from the tab you're currently on, or from all the tabs?

**Comment by 2Pacalypse-** [comment]
Another quick question; should we have a copy of the SC:R settings in our local settings, or is it ok to just read/write from their settings file?

**Comment by neivv** [comment]
The way I was thinking of implementing it was that we'd have our own settings file that contains the settings configurable through Shieldbattery, and patching SC:R's config with that at runtime.

That being said, I think there wouldn't be any issues with just having the app read/write the SC:R config file which would avoid having to hook the code around that.

So it's mainly just a matter of whether we want stay in sync with user changing SC:R settings outside shieldbattery (and just accessing the SC:R config), or wanting shieldbattery settings be separate settings that override other SC:R side changes.

I can't really come up with a reason why we'd want separate settings as long as they behave identically with regular SC:R, so imo just editing the file in Documents/Starcraft is better.

**Comment by neivv** [comment]
Also, should we even have game speed configurable? We have always just hardcoded it to Fastest.

**Comment by 2Pacalypse-** [comment]
I don't think we really _need_ the game speed configuration, but if the game is just reading that from its settings file, I don't really see a reason to purposefully remove it. Unless we override that setting when setting up the game, in which case I can see a reason to remove it.

Another thing that crossed my mind related to copying SC:R settings to our own file or just read/writing its file; users can change settings from within the game or when launched with the battle.net launcher. And we need to at least keep the settings in sync when changed within the app and within the game that's been launched through SB. So having a copy of the SC:R settings might complicate things a bit with keeping things in sync.

**Comment by tec27** [comment]
> So you wouldn't put 'Game Speed' under the Input tab at all? I guess it would make more sense under the Gameplay tab.

We wouldn't have Game Speed at all. This setting is completely out of place in this dialog, it controls the speed of the game when running in single player modes (which can also be changed ingame, and with + and -). We don't expose a way for users to change this with hosting games either, we only run the game on Fastest.

> Do you think we should save the changed settings only from the tab you're currently on, or from all the tabs?

All tabs. You probably want to pull the actual state up a level so that it encompasses the whole dialog, and the relevant parts get passed to each tab's components.

> Another quick question; should we have a copy of the SC:R settings in our local settings, or is it ok to just read/write from their settings file?

I was thinking about this earlier today, and I think users will actually probably expect that we write to/read from the normal file. Originally my thought is that we *wouldn't* do that, that we'd hook the game's reads/writes to go to our own file instead when running in ShieldBattery, but upon further thought, users probably don't operate with that mental model.

**Comment by 2Pacalypse-** [comment]
> I was thinking about this earlier today, and I think users will actually probably expect that we write to/read from the normal file. Originally my thought is that we _wouldn't_ do that, that we'd hook the game's reads/writes to go to our own file instead when running in ShieldBattery, but upon further thought, users probably don't operate with that mental model.

Yeah, I was thinking of implementing a watcher on StarCraft's settings file, similar to how we do it for our own local settings file. Do you think that approach makes sense?

**Comment by tec27** [comment]
Yep, that'd probably be the way to do it

**Comment by 2Pacalypse-** [comment]
Looking at the screenshots above, can you help me make a list of all the settings that we want to add to be configurable through the app? So far I have:
- Speed tab - everything except Game Speed
- Sound tab - everything except Original 1998 Campaign
- Video tab - everything
- Game tab - everything except Mature Language Filter, Show Bonus Skins, Friends Presence Text Notifications
- Network tab - nothing

Also, should we make the UI of those settings follow the UI they have in SC:R, i.e. in two columns? And finally, some of these settings have tooltips that explain the options in greater detail, but I _really_ don't feel like implementing the tooltip component atm :d

**Comment by tec27** [comment]
I would just try to build a reasonable UI, I don't think we need to copy the structure from SC:R (or even the naming of the settings or anything). I don't think the decisions they make around this stuff are particularly good or anything.

**Comment by 2Pacalypse-** [comment]
Done in https://github.com/ShieldBattery/ShieldBattery/commit/d1589443c4b440641e8eec9860bc02ac7d90da29
