### ISSUE TITLE
Set up something to run tests for PRs

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#519]
Github Actions, Travis-CI, something else. Don't really care much what, as long as it happens automatically for PRs so that we don't have to remember to check every time.

**Comment by 2Pacalypse-** [comment]
I've setup Github Actions in this file: https://github.com/ShieldBattery/ShieldBattery/blob/master/.github/workflows/tests.yml
But I made it run on every pushed commit, instead of just when PRs are open. Is that ok?

**Comment by neivv** [comment]
I think you still want to set it to run in `pull_request` events in addition to `push`. I believe it currently wouldn't run tests if somebody who doesn't have write access to this repo made a PR from their fork?

**Comment by 2Pacalypse-** [comment]
Oh that's a good point. Added `pull_request` event as well now.

**Comment by tec27** [comment]
pushed commits + PRs sounds good to me

**Comment by 2Pacalypse-** [comment]
Then this is now done!

The only slight annoyance is that the tests seem to run twice now when we make PRs? But oh well, it's not that big of a deal I guess.
![image](https://user-images.githubusercontent.com/4757944/95013753-99a0ea00-0642-11eb-8a4f-536404c88d36.png)
