### ISSUE TITLE
Wrap `pg` clients to catch syntax errors and log long-running queries

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#525]
If you introduce a syntax error in a query right now it's pretty hard to track down, often the error just ends up getting thrown to the client with most of the context removed. Would be good to actually wrap the clients we get from the database pool so that we can catch and log those errors with context. I think some relevant stuff (including a list of error codes that we'd probably want to handle) is here: https://kb.objectrocket.com/postgresql/postgresql-node-errors-949

While we're doing that, it'd probably also be good to log queries that take longer than a certain time so that we can start figuring out where we need to optimize/change things. (In the future we could probably push this data elsewhere that would be more queryable and/or enable the pg_stat_statements stuff but for now that seems overkill)

**Comment by williamhammond** [comment]
I noticed some long [query logging](https://github.com/ShieldBattery/ShieldBattery/blob/master/server/lib/db/index.ts#L70) , and it looks like the error is showing what's happening by now where.

```
{"level":50,"time":1622765137336,"pid":18212,"hostname":"DESKTOP-8GER2KL","err":{"type":"DatabaseError","message":"column \"asdfchannel_name\" does not exist","stack":"error: column \"asdfchannel_name\" does not exist\n    at Parser.parseErrorMessage (C:\\Users\\willi\\Code\\ShieldBattery\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.
handlePacket (C:\\Users\\willi\\Code\\ShieldBattery\\node_modules\\pg-protocol\\src\\parser.ts:188:21)\n    at Parser.parse (C:\\Users\\willi\\Code\\ShieldBattery\\node_modules\\pg-protocol\\src\\parser.ts:103:30)\n    at Socket.<anonymous> (C:\\Users\\willi\\Code\\ShieldBattery\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (events.
js:376:20)\n    at Socket.emit (domain.js:470:12)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","length":116,"name":"error","severity":"ERROR","code":"
42703","position":"15","file":"parse_relation.c","line":"3349","routine":"errorMissingColumn"},"msg":"unhandled rejection"}
```

Is this ticket ready to be closed out, or are you envisioning some additional logging that'd give either the full failing query or a stack trace back to the original call?

**Comment by williamhammond** [comment]
Or more comprehensive usage of things like https://github.com/ShieldBattery/ShieldBattery/blob/master/server/lib/api/users.js#L107?

**Comment by tec27** [comment]
Long query logging was a small part of it, but the main point of this issue is to catch things like syntax errors in queries. If you click the link in the first post here, it talks about handling various types of errors, logging the queries that caused them, etc.
