### ISSUE TITLE
Add a way to use redux devtools with the electron app

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#531]
I was planning on integrating remote-redux-devtools, but it looks to be sort of abandonware (the server it uses for connecting the devtools + client has had an expired SSL cert for a while). There are ways around that, but they seem more involved than I'd like (running a local server, etc.).

I don't have much preference for the way this gets done as long as it is simple/straightforward (at least as simple as the React devtools usage) for us to use and maintain. One option that looks potentially appealing is just including redux-devtools in the app and rendering the component ourselves.

**Comment by 2Pacalypse-** [comment]
Done in 78e843514772ec68f5b8a880d69f5eaf74ce5204
