### ISSUE TITLE
Make the Tabs component use actual values instead of array indices for its items

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#535]
Currently the Tabs component is quite simple because it uses array indices of its children (TabItems) to calculate which tab is active, which is done here:
https://github.com/ShieldBattery/ShieldBattery/blob/05df46b697d9061ef98325f4834e9d007a6b84f6/client/material/tabs.jsx#L119-L125

This simplifies the usage of the Tabs component since TabItems have an implicit value. However, there are some use cases where having an explicit value on TabItems would be preferable. For example, when we want to display a dynamic amount of TabItems, based on some condition; like we do in the Settings dialog.

To make this use case easier to use, the Tab (and TabItem) components should be expanded so that the TabItem component receives a `value` prop and the Tab component receives a comparator function to calculate when a tab is active (defaulting to a simple equality check). I'm pretty sure we're already doing this exact thing in the Select component so that can be used as an inspiration.

Additionally, we could even implement it in a way that the Tab component supports both implicit and explicit values on its TabItems. If an explicit value is set on a TabItem use the comparator function to check which tab is active, and if no values are set, use the array indices as an implicit value as it is now. Although this might complicate the tabs usage a bit since a mixed approach would probably have to be guarded against, so implementing this is not a requirement.

**Comment by tec27** [comment]
This was done a long time ago I think :)
