### ISSUE TITLE
Migrate componentWillReceiveProps and componentWillUpdate usages to non-deprecated APIs

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#544]
We'll need to do this before moving to React 17.x, which would be nice to do soon. We could just move them to the `UNSAFE_` variants but this also makes the linter unhappy, so I'd prefer to do the actual migration instead.

**Comment by 2Pacalypse-** [comment]
Done in 0e3251ae9b65805f0736cfad4d1c3128346054d7, e809d62b393ed3fc7d6a5538edb1dbdd8e254caf, 191b1bbdea59c9de6c5542cbffddfff052793ec0, 24aa18df731a24c5eb7f9b25731bab0c032e51dc, b2ca9a3235c86101f332cd6765083a1ca9ef1711, and 115b5a83dc807b8077e9ddd25e34130e4331a2a1
