### ISSUE TITLE
Make entire map tile in map browser clickable

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#546]
These tiles definitely feel like they should be clickable, probably should take you to the map details dialog.

(Relatedly, the map image in the map details dialog should probably be clickable and take you to the larger map image preview?)

**Comment by 2Pacalypse-** [comment]
Fixed in https://github.com/ShieldBattery/ShieldBattery/commit/c0fa7ef62aa6da0acd92026e08c56070fc0bb3f0
