### ISSUE TITLE
Make the map image dialog give the image the full space

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#547]
Ideally this would maybe display the map name + close button overlaid over the map image (text protected in some way, either via shadow/outline or a scrim). The big thing is make it so there's no scrolling and the image is the entirety of the content area of the dialog. May require some reworking/duplication of Dialog components.

**Comment by 2Pacalypse-** [comment]
Done in ba56af6f2d163949bc8a32c07756e35af2f31c73
