### ISSUE TITLE
Make observers in lobbies work for SC:R

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#571]
These are currently broken, either we need to use the now built-in feature to support these, or we need to re-reverse all the necessary things to support our better version. For now we're disabling these forcefully in the lobby API (which already supported configuring these to be off).

**Comment by neivv** [comment]
The usual SC:R observing *may* start to work just by assigning observers from player index 12 (id 128) forward.

May even be if we assign one observer "properly" to slot 12, but the local player id on every observer's game to 128, the game stays stable and allows more than 4 observers (So we wouldn't have to even change app/server lobbies).

Probably best to attempt that first.

**Comment by 2Pacalypse-** [comment]
If we use the SC:R's built-in support for observers, does that mean we can have observer support for game types other than Melee working out of the box too?

**Comment by 2Pacalypse-** [comment]
Done in 11e9317d8c34c6c0e298aa7a040338b5dcc14515
