### ISSUE TITLE
Activity overlays + window controls can be confusing

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#615]
When opening an activity overlay (e.g. Find match), there's no clear way to close the overlay. Given that the window controls gain the overlay's background color, it becomes tempting to click the close icon there, thereby closing the window to the system tray.

We should probably:

1) Add a close or a back button to the overlay title (similar to the way things are in Find Match -> Map selection)
2) Add a blue-ish background color to the window controls so that it's obvious they aren't controls for the overlay

**Comment by GrantJenk** [comment]
How do you feel about making it so that the top of the overlay is just below the app bar?

**Comment by tec27** [comment]
I'd have to see how it looks I guess :) I can't recall my reasoning for making them overlap in the way they do, though, so I think potentially that could be fine

**Comment by GrantJenk** [comment]
Here's what I came up with:
![below-app-bar](https://user-images.githubusercontent.com/43507279/111056894-9f4bf880-8448-11eb-840c-e0ec79b2e8ce.png)

As opposed to a blue background:
![blue-background](https://user-images.githubusercontent.com/43507279/111056918-cc98a680-8448-11eb-83e9-c92559c75ae6.png)

**Comment by tec27** [comment]
I think of the two I definitely prefer the first one, let's go with that :) If you want to make that change (or already have it! :) ) feel free to make a PR!

Thanks for putting these together!

**Comment by GrantJenk** [comment]
No problem! I'll submit the PR soon :)
