### ISSUE TITLE
Verification email requires login, after logging in CSRF token fails

### ISSUE THREAD

**Issue by alexpineda** [ShieldBattery/ShieldBattery#617]
Minor issue I ran into.

Steps
1) Clicked send verification email
2) Verification email arrived
3) Clicked on link
4) Received message, must be logged in for verification email
5) Logged in, (maybe redirected to verification?) -> received messaged CSRF token failed (or something like this)
6) Re-clicked link, worked.

**Comment by tec27** [comment]
Duplicate of #605
