### ISSUE TITLE
Use list virtualization for the chat user list

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#628]
This is especially noticeable on the real server: each of the user list entries takes up ~28k in the JS heap for me. Multiplied by thousands of users, this adds up quickly :)

We should virtualize this list to only render what's visible. I *believe* we have a component elsewhere in the app that does this, can't remember for sure though.

**Comment by neivv** [comment]
> I believe we have a component elsewhere in the app that does this, can't remember for sure though.

The file browser uses a list component from `react-virtualized`.
