### ISSUE TITLE
Add a small image in the page metadata for Twitter

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#633]
Need to look up what they're looking for, but the current embed that works for Discord shows no image on Twitter

![image](https://user-images.githubusercontent.com/360513/111056809-e92be300-8436-11eb-893d-d8d768dd03ff.png)

**Comment by GrantJenk** [comment]
Right now, it's using a relative path to the image. Perhaps an absolute path is needed? e.g. `https://shieldbattery.net/images/logo-and-text-1200x630.png`

**Comment by tec27** [comment]
Yep, realized that as well after reading other people's experiences :)
