### ISSUE TITLE
wine: JavaScript error while installing ShieldBattery 7.0.11

### ISSUE THREAD

**Issue by AleXoundOS** [ShieldBattery/ShieldBattery#665]
![wine](https://user-images.githubusercontent.com/464913/114303250-d9ef9200-9ad5-11eb-98ca-d1a19c72533c.png)

```console
$ wine --version
wine-5.0 (Staging)
$ echo $WINEARCH
win64
$ wine ShieldBattery-setup-7.0.9.exe
```

*I know that running under wine is not announced yet. Just a report.*

**Comment by AleXoundOS** [comment]
Launching `ShieldBattery.exe` directly:
```console
$ wine "$HOME/.wine-sb/drive_c/users/alex/Local Settings/Application Data/Programs/shieldbattery-app/ShieldBattery.exe"
```
results in
![wine2](https://user-images.githubusercontent.com/464913/114315733-ea6d3000-9b08-11eb-8476-077d09012ea6.png)

**Comment by AleXoundOS** [comment]
Ah, ok the Documents folder issue is easily fixed with setting the link in winecfg:
![settings the Documents folder manually in winecfg](https://user-images.githubusercontent.com/464913/114315890-b9412f80-9b09-11eb-8c1a-41b4364daceb.png).

Further attempts to run `ShieldBattery.exe` result in no visible response. Though, I've captured the [wine log](https://github.com/ShieldBattery/ShieldBattery/files/6292455/wine-log.txt).

**Comment by AleXoundOS** [comment]
> Further attempts to run ShieldBattery.exe result in no visible response.

So if I run `wine ShieldBattery.exe` from `users/alex/Local Settings/Application Data/Programs/shieldbattery-app` nothing happens visually, but the process keeps running:
```
C:\users\alex\Local Settings\Application Data\Programs\shieldbattery-app\ShieldBattery.exe --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=652,700766826983108305,9683776167860616152,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=network --standard-schemes=shieldbattery --secure-schemes=shieldbattery --bypasscsp-schemes --cors-schemes=shieldbattery --fetch-schemes=shieldbattery --service-worker-schemes=shieldbattery --streaming-schemes --mojo-platform-channel-handle=980 /prefetch:8
```

The `users/alex/Application Data/ShieldBattery/logs/app.0.log` contains:
```
[2021-05-05T16:45:08.486Z]      <system>        Logging started
[2021-05-05T16:45:08.486Z]      <system>        Version: 7.0.11
[2021-05-05T16:45:08.544Z]      <info>  Checking for update
```

**Comment by 2Pacalypse-** [comment]
We now have an (unofficial) support of Wine. Check out the #development channel on our Discord for more info.
