### ISSUE TITLE
Move react-virtualized usages to react-windowed

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#690]
It'd be nice to not pull in two libraries for this same purpose, and react-windowed is better suited to our purposes, along with not being based around inline styles and specific class names for customization.

**Comment by tec27** [comment]
The two places still using react-virtualized are:

- The user list in chat channels
- The file list in the file browser

**Comment by tec27** [comment]
User list is fixed now, file list still needs to be updated

**Comment by 2Pacalypse-** [comment]
Done in https://github.com/ShieldBattery/ShieldBattery/commit/1d2e6b763bec4ad3d5345faef381b07f3c04a7dd
(Sort of, we actually moved to a completely new library, react-virtuoso)
