### ISSUE TITLE
Add a way to sync the `server/public/` folder contents to DO Spaces on server startup

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#718]
We've avoided it thus far, but eventually with avatars and such, we're really going to want a way to ensure certain files are available on the CDN for a particular version (so we can manage these in code and not have to make that system super dynamic). I think a decent option for that is to upload a particular folder to our CDN and keep it up to date on each deploy (this has the added benefit of letting us serve some larger files from the CDN, like the intro video).

`s3cmd` looks like a decent option for doing this. We could update the Dockerfile to pull this in/make it available, and start up a separate container (similar to the DB migration one) to sync things over.

**Comment by 2Pacalypse-** [comment]
Done in 340f01801a7ec5d6d48cb92f0196800446ab3173
