### ISSUE TITLE
Add a search box to the ladder page

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#720]
Not sure if this should function as a filter (show only matching rows) or simply a search with a next/previous button

**Comment by 2Pacalypse-** [comment]
For what is worth, I'd prefer the latter, I think. Although, the former could work too if there was a button or something that can show you a filtered row in the context of the whole table.

**Comment by 2Pacalypse-** [comment]
This was done in https://github.com/ShieldBattery/ShieldBattery/commit/bb2e457f39956dbc1bf7f3f633c11975d9971e97
