### ISSUE TITLE
Add a primary race to the ladder rankings

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#721]
This will require tracking race-specific wins and losses for ranked (or at least total games per race, but the former is probably better long-term), and a migration to populate it from previous data

**Comment by 2Pacalypse-** [comment]
I actually like how the [BGH ladder](http://bghmmr.eu/) calculates its players race here. While I don't know the exact formula that is used, I imagine it's something like this:
- if only one race has % of games > 20% -> show only that race
- if two races have % of games > 20% -> show both those races (this would cover the players with alternate race for mirrors)
- if all three races have % of games > 20% -> show random

20% picked arbitrary, but could be adjusted ^^.

**Comment by 2Pacalypse-** [comment]
Done in 7b01ec920a55a9cf0e9288925ce6c8c68d04a91d
