### ISSUE TITLE
Ripple effect can cause an exception in certain case

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#747]
I'm not even sure what I did to cause this, but looking at the code, it seems to happen in `mouseup` handler of the button component which then tries to deactivate the ripple.

![image](https://user-images.githubusercontent.com/4757944/128888119-dda74e6f-edfe-4be6-aa54-8d344ab3025a.png)

**Comment by tec27** [comment]
Similar error to this one: https://github.com/ShieldBattery/ShieldBattery/issues/742

**Comment by tec27** [comment]
Anyway probably a simple fix for Ripple in particular (springs I dunno if it's our problem or the spring library). We just need to track whether the component is currently mounted and if not, not do anything in `maybeRunDeactivation` if so. (We could also track/cancel any `requestAnimationFrame`s instead, but that seems harder and maybe not worth the effort?). I've definitely seen a hook that simplifies tracking that in particular, I think it's in react-spring (it's a simple `useEffect` anyway but it'd be nice to encode what the specific desire is each time we use it). I'll try to track it down and make use of it here

**Comment by tec27** [comment]
I was misremembering I think, they seem to just use `useOnce` everywhere, which is just a call to `useEffect(fn, [])`. Anyway I changed my mind given that we already had code to cancel timeouts, I just added a couple more request refs and canceled them in that spot.
