### ISSUE TITLE
The game doesn't start.

### ISSUE THREAD

**Issue by LeePC** [ShieldBattery/ShieldBattery#760]
Hello
As soon as the game starts, we'll go to the lobby.
When it comes to languages, Korean breaks down.
I hope you can fix it.
![Screenshot_1](https://user-images.githubusercontent.com/8704225/136544807-16236fb5-f2c9-46c4-b21e-bb447d5956c8.png)

**Comment by LeePC** [comment]
[app.0.log](https://github.com/ShieldBattery/ShieldBattery/files/7310662/app.0.log)
[shieldbattery.0.log](https://github.com/ShieldBattery/ShieldBattery/files/7310663/shieldbattery.0.log)

**Comment by 2Pacalypse-** [comment]
Ok, we'll take a look into it, thx!

**Comment by 2Pacalypse-** [comment]
Can you please share that map with us so we can test?

**Comment by LeePC** [comment]
[Piano.zip](https://github.com/ShieldBattery/ShieldBattery/files/7311543/Piano.zip)

and EUD Map

**Comment by tec27** [comment]
EUD maps should all be working in the next update (7.1.5)
