### ISSUE TITLE
Use lowercase channel name in chat service wherever possible

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#761]
Currently we're using original channel name throughout the service, which requires a DB call to get. This seems awfully wasteful when simply using the lowercase channel name would suffice in most places. The only place where we should use the original channel name, from what I can tell, is saving it in the DB when the channel is created and returning it to users for displaying.

**Comment by tec27** [comment]
Alternatively, give channels a unique ID that is not their name and use that (I know we have talked about this before)

**Comment by 2Pacalypse-** [comment]
If we do that, would we still use names in routes/urls/links; or just use `channelId` everywhere?

**Comment by tec27** [comment]
You'd probably have to or it wouldn't serve much use for solving this issue, since you'd just have to do the lookup on the server every time. (When you suggested this before, you *wanted* it in the URL so that escaping would be less of an issue)

**Comment by 2Pacalypse-** [comment]
This was done in https://github.com/ShieldBattery/ShieldBattery/pull/852
