### ISSUE TITLE
[Question] Getting started

### ISSUE THREAD

**Issue by T1mL3arn** [ShieldBattery/ShieldBattery#763]
Let's say I want to contribute js-related things, but don't want to install Visual Studio and have deal with c++ and rust related code. Is there any workflow for that? Precompiled versions of such dependencies? Can I just skip c++/rust env setup and expect the rest things just work ?

**Comment by 2Pacalypse-** [comment]
Yes, I'm fairly sure this is possible, but it will require a bit of experimentation. Here are some tips off the top of my head.

The rust related code is completely isolated so you can completely ignore it unless you plan on trying to start a game. Although some UI elements might be disabled if the game code files are not properly built, but you can always just turn those checks off in the UI if you need to inspect how the elements look/behave.

C++ side of things is a bit more complicated. There is only one place where we still use C++, and that is in a native node.js addon that we use to create the starcraft process and inject our .dll into it. This addon will be built when you install node.js dependencies in the `app` folder. I'm not sure in what way that will fail if you don't have a C++ compiler on your computer. Besides the obvious thing of the addon not being built, I would hope all other dependencies being installed successfully. Then you would "only" have to comment out the code where we import the said addon, and places where it's used, which could all be found in this file:
https://github.com/ShieldBattery/ShieldBattery/blob/master/app/game/native/process/index.js

However, I think you still might need the C++ compiler for some other native dependencies that we use, especially on the server side. I'm not sure if those are shipped precompiled or not these days. This should be a standard node.js flow though, if you ever worked with it. You could also use the Docker setup to sidestep some of these dependencies.

Honestly, the best approach would probably be to just try stuff and see where it breaks :). Btw, it's important to note that if you setup C++/Rust side to make things work, you don't have to deal with it more than that and can work on just JS-related things after that.

**Comment by tec27** [comment]
Not totally sure how these older Docker tools work, but maybe they create a separate network adapter instead of mapping to the host machine? Have you tried using the `Access URL` from that screenshot for your `DATABASE_URL` in `.env` (instead of `127.0.0.1`)?

Seems like from [this](https://dzone.com/articles/how-to-create-a-docker-machine-with-a-bridged-netw) you could set the VM up to map to the host machine as well, but I think your current setup would work fine if you update the IPs for the DB and Redis servers.

**Comment by T1mL3arn** [comment]
>Have you tried using the Access URL from that screenshot for your DATABASE_URL in .env (instead of 127.0.0.1)?

At first it didnt work, but after containers were recreated it seems working. But...

```bash
yarn run start-server
yarn run v1.22.15
$ node ./server/index.js | node ./server/utils/pino-pg | pino-pretty -c -t
pino-pg: Failed to connect to PostgreSQL server. error: password authentication failed for user "shieldbattery"
```

After experimenting with passwords I found that  I have to use `POSTGRES_SUPER_PASSWORD` in `DATABASE_URL` instead of `SB_DB_PASSWORD` to connect to db server. Though GETTING_STARTED proposes this:

`DATABASE_URL=postgres://shieldbattery:[SB_DB_PASSWORD]@localhost:5433/shieldbattery` 

For me it connects only with this:

`DATABASE_URL=postgres://shieldbattery:[POSTGRES_SUPER_PASSWORD]@localhost:5433/shieldbattery`

Is this a mistake in docs or I misunderstood something ?

**Comment by T1mL3arn** [comment]
Trying to create an account gives me server error

```shell
Error: No rows returned at addMessageToChannel (C:\ShieldBattery\server\lib\chat\/chat-models.ts:205:13)
```

**Comment by T1mL3arn** [comment]
Finally it works! Thanks.
