### ISSUE TITLE
Allow SB client to be registered for *.rep files

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#769]
This would register SB in Windows as the default replay file handler (optionally, perhaps we could provide a button to do it in settings and offer to do so on first launch?). When a replay file is opened with SB, it should go through the normal replay launch process (as if it had been selected from the replay overlay).

**Comment by T1mL3arn** [comment]
How do I know when associated file was open? There is [`open-file`](https://www.electronjs.org/docs/latest/api/app#event-open-file-macos) event but it is only for macos.

**Comment by tec27** [comment]
I think on Windows it would launch a new instance of the application with an argument set (`process.argv[1]` would be the file path, probably? although we'd need to ensure it handles the 'start minimized' flag and such as well).

We check at launch time if the app is already running, and if so, send it a message to bring it to the foreground and quit out of the new instance:
https://github.com/ShieldBattery/ShieldBattery/blob/master/app/single-instance.js#L26

I'd probably approach this by expanding that code to pass a couple different messages depending on the launch arguments:

  - Bring to foreground
  - Open replay file

Then we'd just have to add whatever handling to that second event to show whatever UI, launch the game, etc.

**Comment by T1mL3arn** [comment]
At this moment, an opened replay starts only if a user is logged in. Not everyone checks "remember me" and it is also strange to not being able to watch replays in sort-of "offline" mode. How to handle this case? Create some dummy local user? Postpone watching replay until logging in (with redux middleware) ?

**Comment by tec27** [comment]
Yeah, the local user doesn't really matter when watching replays anyway. I'd probably just give them an empty string username and a user ID of 0. Seems better to do that than to require a user to log in right now (although eventually we will likely show some replay information rather than immediately launching the game, so we may need to re-think that decision down the road)

**Comment by T1mL3arn** [comment]
Also, is it necessary to handle some complex scenarios when watching a replay is requested during logging in? Like, shb opens with replay watch request, and a user has checked "remember me" so the user logins immediately and the actual `startReplay()` action might fire in the middle of auth process.

**Comment by tec27** [comment]
I wouldn't really worry about it at this point. At the point the `startReplay` fires, if the store has a user, use that, if not, pass the empty one.
