### ISSUE TITLE
lobbyPreferences gameSubType is not properly restored

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#782]
This gets sent to the server and returned properly (e.g. if I set a top v bottom to `1`, I get that value back) but doesn't seem to make it into the form correctly when creating a subsequent lobby (it still initializes to `2v2` on a 4 player map, instead of `1v3`)

**Comment by 2Pacalypse-** [comment]
I can't seem to reproduce this anymore so I'll assume it was fixed at some point during the refactor of create-lobby component. Maybe in [this commit](https://github.com/ShieldBattery/ShieldBattery/commit/01907893da452b9e08dd3fdaaa4c8e400df63b41)?
