### ISSUE TITLE
Map details editor doesn't allow empty descriptions, but empty descriptions are valid

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#786]
You can currently upload a map with an empty description, and everything works fine, except:

1) View map details for the map
2) Edit the name
3) Save the name

Expected: Saving the name works
Actual: 400 Bad request, "map description can't be empty"

**Comment by claytondicks** [comment]
If empty descriptions are allowed, is there any reason for the server to throw the error when description is empty?

**Comment by 2Pacalypse-** [comment]
No, that restriction needs to be removed (and made sure that it doesn't break anything else).

**Comment by 2Pacalypse-** [comment]
Done in #855
