### ISSUE TITLE
Drop `invites` table

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#799]
There's no code that uses this any more, once we're sure we're done with it (I think we are now but I want to sleep on that a bit), we should drop it. This issue is just so I don't forget

**Comment by tec27** [comment]
Can probably remove the "acceptInvites" permission while we're at it

**Comment by 2Pacalypse-** [comment]
Done in 4132fd4c0486d354525f059c807b8d13c38b73f4
