### ISSUE TITLE
User profile shows indefinite loading in some cases

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#828]
Steps to reproduce:
- Left-click on user's name in chat
- Before the user's stats are shown, click on "View profile"
- User's profile page shows indefinite loading

**Comment by 2Pacalypse-** [comment]
I actually debugged this now, but I'm not sure what's the best way to go about fixing it.

Basically what happens is:
- user-profile-overlay.tsx requests user's profile in this effect: https://github.com/ShieldBattery/ShieldBattery/blob/4646e446598ddd6e2e4c2f62b0a832424e5a6834/client/users/user-profile-overlay.tsx#L199-L215
- as soon as you click "View profile", the cleanup function in above effect runs which sets the request as aborted
- user-profile.tsx requests user's profile as well in its own, similar effect
- but since the previous request didn't get to cleanup yet, the action-creator detects that there already is a request in progress for this user and just returns: https://github.com/ShieldBattery/ShieldBattery/blob/4646e446598ddd6e2e4c2f62b0a832424e5a6834/client/users/action-creators.ts#L56-L74

So the issue is that this code in action-creator that checks if there are any loads in progress, doesn't handle the case of what happens if some of those requests get aborted. And I think we use this logic in a few places already as an optimization. But as I said, I'm really not sure what's the best way to fix this.

**Comment by tec27** [comment]
is the issue just that there's no time to run async completions between aborting and rendering the new thing? Does adding `await Promise.resolve()` or something similar as the first part of the `abortableThunk` body fix it?

**Comment by 2Pacalypse-** [comment]
I'm not sure about what the exact timings _should_ be here, but here's how I tested this:
- In `user-profile-overlay.tsx` I added this:

![image](https://github.com/user-attachments/assets/dbcbb3e6-d40f-4522-a3d0-14ee6953b55a)
- In `user-profile.tsx` I added this:

![image](https://github.com/user-attachments/assets/986c3b78-a2a3-4cb2-9e1e-33a0dd3db0de)
- In `user/action-creators.ts` I added this:

![image](https://github.com/user-attachments/assets/9cf5e247-b587-49fa-ac2d-b3c0ba8c30fc)

And then when testing, I opened user profile overlay, waiting ~2 seconds, and then clicked on View profile. This is the output:

![image](https://github.com/user-attachments/assets/540bd864-4baa-4fcf-a4f5-c7f8a27a2893)

**Comment by 2Pacalypse-** [comment]
>Does adding await Promise.resolve() or something similar as the first part of the abortableThunk body fix it?

Assuming I did this correctly, not it doesn't.

**Comment by tec27** [comment]
The modified code you wrote doesn't abort in the same way the "real" one does, the timeout will never abort, so this isn't a realistic test. Either use the dev tools to slow the request down or modify the server to respond slowly

**Comment by 2Pacalypse-** [comment]
The same order of operations happen then as well from what I can see.

This is the code I used now to test:

![image](https://github.com/user-attachments/assets/46297a8e-d2da-494f-a0af-259645c45042)

And this is the console output:

![image](https://github.com/user-attachments/assets/96f49e41-5e0b-4103-9428-60b5df2064f5)
