### ISSUE TITLE
Feature request: block user

### ISSUE THREAD

**Issue by innerspirit** [ShieldBattery/ShieldBattery#851]
Hi, so I just played for the first time and out of 5 games, 2 people started whispering me after the game angry things, one of them with racist stuff. Is there a way to block/report users? I haven't found it.

**Comment by 2Pacalypse-** [comment]
We haven't gotten around to implementing it yet, but it's very high on our priority list.

**Comment by innerspirit** [comment]
by the way do disconnects count as loss?

**Comment by innerspirit** [comment]
I will answer myself: no, there's a player with 3 disc and 2-1 record in the top 30, clearly the purposeful discs are not affecting his rating

**Comment by tec27** [comment]
Disconnects do count as a loss, however currently there is some delay in applying those losses in 1v1 games (approximately 6 hours). This is mainly to ensure that both players have an opportunity to report the results for the game. In the future this delay will be brought down to a much shorter timeframe, but it requires more integration with our game servers to detect when games are still running.

(Side note, this isn't really a great way to have discussions, if you have questions such as these that don't relate to the issue filed, it'd be better if you ask them in our Discord)

**Comment by tec27** [comment]
Implemented in 4cae077a476adf7f2f82d1d91fff084b78371105
