### ISSUE TITLE
Can It support language selection?

### ISSUE THREAD

**Issue by woodgreat** [ShieldBattery/ShieldBattery#880]
support language like select English ,Chinese ,Tai  ,korea ...

**Comment by woodgreat** [comment]
got ,thanks

**Comment by 2Pacalypse-** [comment]
ShieldBattery now supports language selection.

If you wish to help improve our translations, please read this guide: https://github.com/ShieldBattery/ShieldBattery/blob/master/docs/TRANSLATION_GUIDE.md

**Comment by woodgreat** [comment]
OK,

**Comment by woodgreat** [comment]
I reviewed the chinese translated by others ,is done ! words correct at most ,you can use it at first !
