### ISSUE TITLE
what's the docker compose version of "Getting Started"

### ISSUE THREAD

**Issue by woodgreat** [ShieldBattery/ShieldBattery#882]
in "Getting Started" the line:

Then, from the root of this repository, run:

$ docker-compose up -d

----------------------------
but ..
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service def
initions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

where is the error?

**Comment by 2Pacalypse-** [comment]
Which operating system / docker version are you using? Have you tried updating your docker?

**Comment by woodgreat** [comment]
yes, I use ubuntu ,Ubuntu 16.04.7 LTS , Docker version 18.09.7, build 2d0083d ,newest version

**Comment by woodgreat** [comment]
I think "Getting Started" should tips supported Docker version ,right?

**Comment by woodgreat** [comment]
solved !

    update docker to version 20 or above
    change the file example.env to .env (just no front part_
    then ,try "docker-compose up -d"
