### ISSUE TITLE
At "Getting Started" there are some conficts

### ISSUE THREAD

**Issue by woodgreat** [ShieldBattery/ShieldBattery#883]
eg. 
Getting Started:
    DATABASE_URL=postgres://shieldbattery:[SB_DB_PASSWORD]@localhost:5433/shieldbattery
    SB_REDIS_HOST=localhost
    SB_REDIS_PORT=6380

================================================== 
but in /sample.env of our files root : 
# Password used for the postgres super user, used for database maintenance. This is only required if
# you're running the database dependency through Docker; otherwise you can ignore it.
# POSTGRES_SUPER_PASSWORD=SuperSecureDefinitelyChangeThis

# Password used for the user connecting to the shieldbattery database. Has to match the one provided
# in the `DATABASE_URL`. This is only required if you're running the database dependency through
# Docker; otherwise you can ignore it.
# SB_DB_PASSWORD=ExtremelySecureDefinitelyChangeThis

# URL to connect to the postgres database
DATABASE_URL=postgres://username:password@localhost/shieldbattery

# The "main" host for the application, this will be used for generating links
# and other hosts will generally redirect here
SB_CANONICAL_HOST=http://localhost:5555
# The port the HTTP server should listen on
SB_HTTP_PORT=5555

# Whether the HTTP server has an HTTPS reverse proxy forwarding to it (generally
# true for production, but false for development)
#SB_HTTPS_REVERSE_PROXY=false

# A value used to sign session cookies, should be unique per server and kept
# secret
SB_SESSION_SECRET=shhhhhhhh
# Time to keep unused sessions around (in seconds)
SB_SESSION_TTL=2592000

# Host of the redis server
SB_REDIS_HOST=localhost
# Port of the redis server
SB_REDIS_PORT=6379

===================================
the vars:
SB_REDIS_PORT  = 6380 or 6379
 
DATABASE_URL=postgres://shieldbattery:[SB_DB_PASSWORD]@localhost:5433/shieldbattery
or
DATABASE_URL=postgres://username:password@localhost/shieldbattery

which is right?
docker .yaml stop at 
================================
ERROR: Invalid interpolation format for "environment" option in service "db": "POSTGRES_PASSWORD=${POSTGRES_SUPER_PASSWORD:?missing POSTGRES_SUPER_PASSWORD}"
===================================

so,there is a lot of error in tutorial and configure ,
we need fix it , or more detail for manual configuration .
thanks

**Comment by 2Pacalypse-** [comment]
The values in `sample.env` are just an example values (but mostly correct if you're setting up the server manually).
If you're using Docker, then the values mentioned in the `GETTING_STARTED` guide overrule the example values.

So if you're using Docker, you should set your `DATABSE_URL` to `DATABASE_URL=postgres://shieldbattery:[SB_DB_PASSWORD]@localhost:5433/shieldbattery`. Note that the `[SB_DB_PASSWORD]` string should be replaced with whatever you set your `SB_DB_PASSWORD` to, e.g.:
```
POSTGRES_SUPER_PASSWORD=SuperSecureDefinitelyChangeThis
SB_DB_PASSWORD=ExtremelySecureDefinitelyChangeThis
DATABASE_URL=postgres://shieldbattery:ExtremelySecureDefinitelyChangeThis@localhost:5433/shieldbattery
```
As for the redis port, if you're using Docker, you need to set it to `6380`. If you're setting up your server manually, then you need to set it to whatever you configured your `redis` to run on (`6379` by default I think).

**Comment by woodgreat** [comment]
solved !
1. update docker to version 20 or above
2. change the file example.env to .env (just no front part_
3. then ,try "docker-compose up -d"
