### ISSUE TITLE
(record) meet new error , error while loading shared libraries: libatk-1.0.so.0

### ISSUE THREAD

**Issue by woodgreat** [ShieldBattery/ShieldBattery#884]
# yarn run app
yarn run v1.22.19
$ cross-env SB_HOT=1 electron app
/home/sb/ShieldBattery/node_modules/electron/dist/electron: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by 2Pacalypse-** [comment]
This is not really an error that we can fix. The application can only be run on Windows (or through Wine on linux).

**Comment by woodgreat** [comment]
thank you
