### ISSUE TITLE
Error when trying to join a channel which has someone banned in it

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#894]
![image](https://user-images.githubusercontent.com/4757944/222598087-bd8a6be7-7f1c-4b22-ab70-d435a2df96a7.png)

I have one entry in my `channel_identifier_bans`. Trying to join the same channel that is in that entry with a different user produces above error.

**Comment by tec27** [comment]
That's a... very weird error? It's also pointing at `identifier_type` and not `identifier_hash` in the query?

**Comment by tec27** [comment]
I guess apparently column order is the thing they use and not column names? So you need to specify the columns and then select them in that order
