### ISSUE TITLE
Can It support language selection?

### ISSUE THREAD

**Issue by liongis** [ShieldBattery/ShieldBattery#921]
support language like select English ,Chinese?
I am willing to provide Chinese translation, as well as multi-language development assistance.

**Comment by 2Pacalypse-** [comment]
We don't have full support for language selection yet, but we're halfway there.

What we have so far:
- Support for multiple languages (see this commit for initial integration:  https://github.com/ShieldBattery/ShieldBattery/commit/cb7e9a3d44e8404bded4a93a199cab587595a08f)
- Some translation strings added (see this PR for an example: https://github.com/ShieldBattery/ShieldBattery/pull/920)
- Weblate server for adding translations (see this link if you want to help with translating: https://translation.shieldbattery.net/projects/shieldbattery/app/)

What we still need to do:
- Add translation strings for the rest of the application (ExcalZ is working on some of this in that PR above)
- Add language detection plugin for i18next library (should be fairly easy)
- Allow users to change their language in settings (requires rewriting our settings Dialog which I'm halfway through)

**Comment by 2Pacalypse-** [comment]
ShieldBattery now supports language selection.

If you wish to help improve our translations, please read this guide: https://github.com/ShieldBattery/ShieldBattery/blob/master/docs/TRANSLATION_GUIDE.md
