### ISSUE TITLE
Limit the number of joined channels to some reasonable value

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#927]

**Comment by 2Pacalypse-** [comment]
Hmm, what would be the reasonable value here, a 100?

**Comment by tec27** [comment]
I dunno, 50? both of these numbers seem ridiculous from a perspective of what this will be like in our UI currently. I think 100 is definitely too high.

**Comment by 2Pacalypse-** [comment]
Done in a42786b0b6937e46ea5f1958fe6f990585d7e98b

Limited to max 40 joined channels btw.
