### ISSUE TITLE
Limit the number of owned channels to some reasonable value

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#928]
(This should likely be something that's just checked on channel creation, e.g. it wouldn't prevent ownership from being transferred to that user, it would just prevent them from creating new channels. If we don't have a way of transferring ownership without leaving a channel then we may need to think about that a bit)

**Comment by 2Pacalypse-** [comment]
Hmm, should this value be different than the maximum allowed number of joined channels? For example, you're allowed to be in 100 channels at once, but can only create 50 of them yourself?

**Comment by tec27** [comment]
Yes, it should be lower

**Comment by 2Pacalypse-** [comment]
Wouldn't it be pretty easy to circumvent this limit if a user can just use one of their smurfs to transfer the ownership to their main account? I guess saying that out loud made me realize that we should probably not let users transfer the ownership to their alternate accounts :p

**Comment by tec27** [comment]
It wouldn't be extremely hard to circumvent but it would make it a lot more time consuming to do so, which is the goal. I don't really see why we'd prevent users from transferring accounts to smurfs. This can never be fully abuse-proof in a system that allows creating new accounts for free, that is not the goal.

**Comment by 2Pacalypse-** [comment]
Done in a42786b0b6937e46ea5f1958fe6f990585d7e98b

Limited to max 20 owned channels btw.
