### ISSUE TITLE
The game countdown has been canceled

### ISSUE THREAD

**Issue by liongis** [ShieldBattery/ShieldBattery#930]
When The client compiled with the downloaded program code starts the game, the message "The game countdown has been canceled." What is the problem?

**Comment by 2Pacalypse-** [comment]
I'm gonna assume this is the same issue as this https://github.com/ShieldBattery/ShieldBattery/issues/919.

We don't have the time to support custom deployments so you will need to debug this on your own. Sorry.

**Comment by liongis** [comment]
Deployment is not their own, is directly download the lot code, compile directly yarn run dist is https://shieldbattery.net server should be used, can't normal game, download the official shieldbattery installer after installation, Can play normally.

**Comment by liongis** [comment]
Now there are many players in China who need to fight, so we need a Chinese version of The battle platform. We have converted as much English as possible into Chinese. However, after compiling, the program can run normally, but when starting the game, the prompt: "The game countdown has been canceled" will be asked.
We found an interesting place in the process of testing, as long as one party uses the official website client and the other party uses its own compiled client, it can normally start the game and fight.

**Comment by 2Pacalypse-** [comment]
Yeah, I'm not sure what's wrong there. Could be a lot of things.

Btw, we're working on the language support too, so you should probably help us get the official Chinese language support instead of hacking around the client.

You can start translating things for us at this link: https://translation.shieldbattery.net/projects/shieldbattery/app/
