### ISSUE TITLE
Can't upload some EUD maps

### ISSUE THREAD

**Issue by armoha** [ShieldBattery/ShieldBattery#931]
'There was a problem uploading map' while those are not protected (obfuscated) maps

[locErrorTest.zip](https://github.com/ShieldBattery/ShieldBattery/files/11278967/locErrorTest.zip)

[test_unittest.zip](https://github.com/ShieldBattery/ShieldBattery/files/11278973/test_unittest.zip)

**Comment by tec27** [comment]
As discussed in our Discord, the cause looks to be  unsupported compression algorithms in the MPQ format (scm-extractor). Would either need to add support in scm-extractor, or add it in broodmap + migrate to broodmap for our map parsing code.

**Comment by tec27** [comment]
This should work after our next update is deployed, thanks for reporting!
