### ISSUE TITLE
Logging out of the application generates the wrong `nextPath` query in URL

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#941]
![image](https://github.com/ShieldBattery/ShieldBattery/assets/4757944/7b67fa64-ddd4-43d1-a339-fb4ce81f41d4)

It basically runs the `doRedirect` function in LoggedInFilter twice, so the `nextPath` gets nested. I'm not really sure why it does that, or what's the correct solution.

**Comment by tec27** [comment]
Think you could probably just write a much simpler thing than all the `createConditionalRedirect` stuff at this point (and writing something that utilizes hooks probably gives better guarantees on when certain things run).

(`createConditionalRedirect` is only used here + for admin routes, most of which are gone now anyway. I would probably just make the admin routes only render at all if the user is an admin, which removes the need for any conditional redirects there)

The idea behind most of this stuff *I think* was to prevent multiple things from causing a conditional redirect at once. An easier way to do that is probably just to utilize `Redirect` (from wouter) during a render. Unsure what inside of here would cause a double redirect anyway, if the problem still exists with this different approach then you might just need to check if the current url already has a `nextPath` and no-op in the case (but I would verify you ever see that first, not point in writing dead code that increases the complexity of things)
