### ISSUE TITLE
User names in the whispers list should show the user-context-menu on right-click

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#947]
Got a suggestion from SzybkiLopez(GN) that he would like to invite people to a party from his whispers list. I guess that's faster than doing it from the friends list?

But anyway, sounds like a good suggestion to me.

Obviously we can't show the user-profile-overlay on left-click, so this should only work for the right-click. Discord does the same I think.

**Comment by tec27** [comment]
Would probably be good to have more profile info + actions on the whisper page itself as well (where the user list normally is in chat channels)

**Comment by 2Pacalypse-** [comment]
I made a [PR](https://github.com/ShieldBattery/ShieldBattery/pull/1098) that will close the original part of this issue, and I created [another issue](https://github.com/ShieldBattery/ShieldBattery/issues/1099) to track your suggestion.
