### ISSUE TITLE
Chat channels can appear out of join order

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#983]
If the client receives an `init3` event for a channel prior to getting the `chatReady` with all the channel info, I guess something in the reducer ends up out of order. I'm not sure what we're doing there but we should really just have an array of channel IDs in the order we want to display them, and `chatReady` should overwrite whatever is there

**Comment by 2Pacalypse-** [comment]
Fixed in https://github.com/ShieldBattery/ShieldBattery/commit/49af0ad72af64b7ba6c9cd3044ed93a8da1a6ec2
